name: 'dbt_contact_center'
version: '1.0.0'
config-version: 2

profile: 'dbt_contact_center'   # ← New profile name

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "logs"]

models:
  dbt_contact_center:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table